server:
  port: 9000
  error:
    server.error.include-message: always
    server.error.include-binding-errors: always


mail:
  host: localhost
  port: 1025
  username: notifyme
  password: hello

  properties:
    mail:
      smtp:
        ssl:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
