server:
  port: 9000
  error:
    server.error.include-message: always
    server.error.include-binding-errors: always
    whitelabel:
      enabled: false

spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5434/notifyme
    username:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true